-- DishPrompt secure delivery schema for Supabase Postgres.
-- Run this once in Supabase Dashboard -> SQL Editor.

create table if not exists public.delivery_tokens (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  email text not null,
  storage_key text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists delivery_tokens_active_lookup
  on public.delivery_tokens (token_hash, expires_at)
  where used_at is null;

create table if not exists public.processed_webhook_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  event_name text not null,
  created_at timestamptz not null default now()
);

alter table public.delivery_tokens enable row level security;
alter table public.processed_webhook_events enable row level security;

-- No public or anon policies are intentional. The server uses the Supabase
-- service-role key, which bypasses RLS. Never expose that key to the browser.
